### ISSUE TITLE
Реализовать сборщик картинок с яндекса, гугла и бинга, код MODAIB-17

### ISSUE THREAD

**Issue by akumidv** [iondv/tensorflow-dataset#8]
В тензор-флоу нужно реализовать:

* класс задача сбора картинок. Метаданные:
  * выпадающий список яндекс,гугул, бинг.
  * поисковый текст
  *  десятичное поле - кол-во первых скачиваемых картинок.
  *  поле параметров поиска. Пока реад-онли все время, т.е. не реализуем функцию.
* нужно доработать класс объектов, если там еще нет - добавить хешфункцию уникальности картинки. Т.е. чтобы повторные не закачивать.

Делаем на объекте бизнес-процесс. Запустить сборку. Процесс одношаговый., назад не предусматривать. Объект на шаге собрано - все поля заблокированы для реадактирования.

При запуске БП соответственно - запускаем модель парсера через пупитер - модель берем из фрахтов https://github.com/iondv/freight-quote . Засовываем туда пока два парсера, яндекса и гугла картинки. Запускаем поиск, скачиваем первые кол-во картинок, которое указано. Создаем объекты для обучения.

Делаем отсечку. Первую при проверке на режим NODE_ENV=demo - 10 картинок. 
даваемое в деплой, по умолчанию 100 картинок.

**Comment by tseissrd** [comment]
сделал
